import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Extracted Header from page.js - Removed lg: prefixed classes for consistent styling */}
        <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm mb-4"> {/* Removed lg:flex */}
          <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit"> {/* Removed all lg: classes */}
            GitHub Content AIssistant
          </p>
        </div>
        {/* Render the rest of the page content */}
        {children}
      </body>
    </html>
  );
}
